apiVersion: apps/v1
kind: Deployment
metadata:
  name: website
  namespace: website
spec:
  template:
    spec:
      containers:
      - name: website
        image: ghcr.io/o-p-n/website@sha256:22afc8e7bacfc6b6bedca162884a0392667a4ad013e494129e2d0b0ed806de4e
