{
 "title": "serveit / Website",
 "tags": [ "serveit" ],
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  {
   "title": "Indexed files",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(serveit_indexed_files_count{app=\"website\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Indexing runs",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(serveit_indexing_runs_total{app=\"website\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Transaction RTT",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg by(quantile) (serveit_txn_duration{app=\"website\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Requests by path",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "avg by(path) (serveit_txn_requests_total{app=\"website\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Responses by status",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "avg by(status) (increase(serveit_txn_responses_total{app=\"website\"}[1h]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}