apiVersion: apps/v1
kind: Deployment
metadata:
  name: website
  namespace: website
  labels:
    app: website
spec:
  replicas: 3
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: website
  template:
    metadata:
      labels:
        app: website
    spec:
      containers:
      - name: website
        # image:  ghcr.io/o-p-n/website@sha256:2f6398d11eb0d37ce38ff7f7851890d147079dbfadb79da598f02f66e3c67e67
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            memory: "32Mi"
            cpu: "50m"
          limits:
            memory: "64Mi"
            cpu: "200m"
        ports:
        - containerPort: 4000
        - name: web-metrics
          containerPort: 9090
