apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

labels:
  - pairs:
      outer-planes.net/deployment: website

resources:
  - ./namespace.yaml
  - ./deployment.yaml
  - ./service.yaml
  - ./monitor.yaml
  - ./dashboard.yaml
