name: deploy
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "k8s/**"

jobs:
  deploy-k8s:
    name: Deploy image
    runs-on: ubuntu-22.04
    env:
      TUNNEL_SERVICE_TOKEN_ID: "{{ secrets.CF_SERVICE_AUTH_KEY }}"
      TUNNEL_SERVICE_TOKEN_SECRET: "{{ secrets.CF_SERVICE_AUTH_SECRET }}"
    strategy:
      matrix:
        include:
          - environment: public
            hostname: outer-planes.net
            kubeconfig: {{ secrets.KUBECONFIG_PUBLIC }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true
      - name: Setup Tooling
        # TODO: convert into an action
        run: ./.github/scripts/install-tooling.sh
        env:
          INSTALL_PATH: /usr/local/bin
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Start tunnel
        uses: JarvusInnovations/background-action@2428e7b970a846423095c79d43f759abf979a635
        with:
          run: |
            cloudflared access tcp --hostname=kubectl.outer-planes.casa --url localhost:9876
          wait-on: |
            tcp:localhost:9876
      - name: Prepare Kubectl
        run: |
          mkdir -p ~/.kube
          echo -n "{{ matrix.kubeconfig }}" > ~/.kube/config
      - name: Deploy ${{ matrix.environment }}
        run: |
          o-p-n.deployer apply --env ${{ matrix.environment }}
          exit 0