name: deploy
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "k8s/**"

jobs:
  deploy-k8s:
    name: Deploy image
    runs-on: ubuntu-22.04
    env:
      TUNNEL_SERVICE_TOKEN_ID: "{{ secrets.CF_SERVICE_AUTH_KEY }}"
      TUNNEL_SERVICE_TOKEN_SECRET: "{{ secrets.CF_SERVICE_AUTH_SECRET }}"
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true
      - name: Setup Tooling
        # TODO: convert into an action
        run: ./.github/scripts/install-tooling.sh
        env:
          INSTALL_PATH: /usr/local/bin
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Prepare Kubectl
        run: |
          mkdir -p ~/.kube
          echo -n "{{ secrets.KUBECONFIG_PUBLIC }}" > ~/.kube/config
      - name: Deploy public
        run: |
          cloudflared access tcp --hostname=kubectl.outer-planes.casa --url localhost:9876 &
          o-p-n.deployer apply --env public
          exit 0